### ISSUE TITLE
update

### ISSUE THREAD

**Issue by rubenh2905** [andyjjrt/bazaar#1]
hi, does it going to get a update ? like enhancing updated ?

**Comment by andyjjrt** [comment]
Like what? Because hypixel banned me for no reason, I've got tired of maitaining this, but it's good if you have some suggestions

**Comment by rubenh2905** [comment]
are you serious ?, but bazaar data don't need token, so how they banned you ?
my idea is something like https://bazaartracker.com/ to tracking bazaar movements and some raw craft hints but open source and free

**Comment by andyjjrt** [comment]
I have no idea how to get raw craft hint automatically, but this website now have real time price tracking, and due to github actions' restriction, I use 30 minutes interval as the movement chart data. So in conclusion, some of your ideas have already existed.

**Comment by andyjjrt** [comment]
I'm glad if you want to help me get reciepes of items, thus I can add on to the website

**Comment by rubenh2905** [comment]
i want to help but sadly i'm not js dev, i'm java dev

**Comment by andyjjrt** [comment]
Well, I mean the receipe of the items, not about the code, I can actually handle all of them XD.

**Comment by rubenh2905** [comment]
raw craft recipes are not too much, may be it will take 1day to get all of them, but if you want do it dynamically you have to took a look at neu i think
